config/routes.rb
Rails.application.routes.draw do
  resources :ishbers
  root "projects#index"
  resources :tgers
  
  resources :tgs do
    resources :tgers
  end
  resources :yuks
  resources :projects do
    resources :yuks
    resources :tgs
    resources :ishbers
  end
  devise_for :users

end

app/models/ishber.rb
class Ishber < ApplicationRecord
  belongs_to :project
end

app/controllers/ishbers_controller.rb
class IshbersController < ApplicationController
  before_action :set_ishber, only: %i[ show edit update destroy ]
  before_action :set_project, only: %i[ index new ]

  # GET /ishbers or /ishbers.json
  def index
    @ishbers = @project.ishbers
    @ishber = @project.ishbers.new

    
    @ishbers.each do |ishber|
      if ishber.project.user != current_user 
        return redirect_to root_path
      end
    end
  end

  # GET /ishbers/1 or /ishbers/1.json
  def show
  end

  # GET /ishbers/new
  def new
    @ishber = Ishber.new
  end

  # GET /ishbers/1/edit
  def edit
  end

  # POST /ishbers or /ishbers.json
  def create
    @ishber = Ishber.new(ishber_params)

    respond_to do |format|
      if @ishber.save
        format.html { redirect_to project_ishbers_path(@ishber.project) }
        format.json { render :show, status: :created, location: @ishber }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ishber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ishbers/1 or /ishbers/1.json
  def update
    respond_to do |format|
      if @ishber.update(ishber_params)
        format.html { redirect_to ishber_url(@ishber) }
        format.json { render :show, status: :ok, location: @ishber }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ishber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ishbers/1 or /ishbers/1.json
  def destroy
    @ishber.destroy

    respond_to do |format|
      format.html { redirect_to ishbers_url, notice: "Ishber was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ishber
      @ishber = Ishber.find(params[:id])
    end
    def set_project
      @project = Project.find(params[:project_id])
    end
    # Only allow a list of trusted parameters through.
    def ishber_params
      params.require(:ishber).permit(:title, :project_id)
    end
end

app/helpers/ishbers_helper.rb
module IshbersHelper
end

app/views/ishbers/_form.html.erb
<%= form_with(model: ishber) do |form| %>
  <% if ishber.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ishber.errors.count, "error") %> prohibited this ishber from being saved:</h2>

      <ul>
        <% ishber.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 row">
    <%= form.label :title, class: "col-sm-2 col-form-label", style: "display: block" %>
    <div class="col-sm-10">
    <%= form.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= form.label :project_id, class: "col-sm-2 col-form-labe cl", style: "display: block" %>
    <div class="col-sm-10">
    <%= form.text_field :project_id, type: :hidden, class: "form-control" %>
    </div>
  </div>

  <div class="createbutton">
    <%= form.submit "Create Task",class:"submit" %>
  </div>
<% end %>

app/views/ishbers/_ishber.html.erb
<div id="<%= dom_id ishber %>">
  <p>
    <strong>Title:</strong>
    <%= ishber.title %>
  </p>

</div>

app/views/ishbers/edit.html.erb
<br/>
<div class="card" style="width: 80%;">
  <div class="card-header">
    <h1>Editing Tasks</h1>
  </div>

  <div class="card-body">
    <%= render "form", ishber: @ishber %>
  <br>
    <div class="row">
      <%= link_to "Show this Tasks", @ishber, class:"allbuttons col-6 text-center" %>
      <%= link_to "Back to Tasks", ishbers_path, class:"allbuttons col-6 text-center" %>
    </div>
  </div>
</div>

app/views/ishbers/index.html.erb
<br/>
<div class="card" style="width: 80%;">
  <div class="card-header">
    <h1>Tasks</h1>
  </div>
  <div class="card-body">
  <%= render "form", ishber: @ishber %>
  <div id="ishbers">
    <% @ishbers.each do |ishber| %>
      <%= ishber.title %> <br>
        <% if ishber.title %>
        <%= button_to "Delete this tasks", ishber, method: :delete , class:"btn btn-danger btn-hover button rounded-pill p-2 col-3" %> <br>
        <% end %>  
    
    <% end %>
  </div>
  <%= link_to "Back", project_path(@ishber.project_id) , class:"allbuttons" %>
  </div>
  <style>
      .card{
        background: #F8F4E5;
        border: 1px solid #000;
        box-shadow: 15px 15px #ffa580;
      }
      .button{
        padding-left: 20px;
        display: block;
        margin: 0 auto;
        padding: 0 20px;
        background: #ffa580;
        border: 1px solid #000;
        box-shadow: 5px 5px #95A4FF;
      }
    </style>
</div>

app/views/ishbers/new.html.erb
<br/>
<div class="card" style="width: 80%;">
  <div class="card-header">
    <h1>New Tasks</h1>
  </div>
  <div class="card-body">
  <%= render "form", ishber: @ishber %>
  <br>
  <%= link_to "Back to Tasks", ishbers_path , class:"allbuttons"%>
  </div>
</div>

app/views/ishbers/show.html.erb
<br/>
<div class="card" style="width: 80%;">
  <div class="card-header">
    <%= render @ishber %>
  </div>

  <div class="card-body">
    <div class="row">
      <%= link_to "Edit this Tasks", edit_ishber_path(@ishber) , class:"allbuttons col-6 text-center" %>
      <%= link_to "Back to Tasks", ishbers_path , class:"allbuttons  col-6 text-center" %>
    </div>
    <%= button_to "Destroy this Tasks", @ishber, method: :delete, class:"btn btn-danger"%>
  </div>
</div>