config/routes.rb
Rails.application.routes.draw do
  resources :ishbers
  root "projects#index"
  resources :tgers
  
  resources :tgs do
    resources :tgers
  end
  resources :yuks
  resources :projects do
    resources :yuks
    resources :tgs
    resources :ishbers
  end
  devise_for :users

end

app/models/yuk.rb
class Yuk < ApplicationRecord
  belongs_to :project
  has_one_attached :yuker
end

app/controllers/yuks_controller.rb
class YuksController < ApplicationController
  before_action :set_yuk, only: %i[ show edit update destroy ]
  before_action :set_project, only: %i[ new edit destroy index ]

  # GET /yuks or /yuks.json
  def index
    @yuks = @project.yuks
    @yuk = @project.yuks.new

    
    @yuks.each do |yuk|
      if yuk.project.user != current_user 
        return redirect_to root_path
      end
      
    end
    
 
  end

  # GET /yuks/1 or /yuks/1.json
  def show
  end

  # GET /yuks/new
  def new
    @yuk = @project.yuks.new
  end

  # GET /yuks/1/edit
  def edit
  end

  # POST /yuks or /yuks.json
  def create
    @yuk = Yuk.new(yuk_params)

    respond_to do |format|
      if @yuk.save
        format.html { redirect_to project_yuks_path(@yuk.project), notice: "Yuk was successfully created." }
        format.json { render :show, status: :created, location: @yuk }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @yuk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yuks/1 or /yuks/1.json
  def update
    respond_to do |format|
      if @yuk.update(yuk_params)
        format.html { redirect_to yuk_url(@yuk), notice: "Yuk was successfully updated." }
        format.json { render :show, status: :ok, location: @yuk }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @yuk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yuks/1 or /yuks/1.json
  def destroy
    @yuk.destroy

    respond_to do |format|
      format.html { redirect_to yuks_url, notice: "Yuk was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yuk
      @yuk = Yuk.find(params[:id])
    end
    
    def set_project
      @project = Project.find(params[:project_id])
    end

    # Only allow a list of trusted parameters through.
    def yuk_params
      params.require(:yuk).permit(:yuker,:project_id)
    end
end

app/helpers/yuks_helper.rb
module YuksHelper
end

app/views/yuks/_form.html.erb
<%= form_with(model: yuk) do |form| %>
  <% if yuk.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(yuk.errors.count, "error") %> prohibited this yuk from being saved:</h2>

      <ul>
        <% yuk.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3 row">
    <%= form.file_field :yuker %>
  </div>
  <div class="col-sm-10">
    <%= form.text_field :project_id, type: :hidden, class: "form-control" %>
  </div>
  <div class="createbutton">
    <%= form.submit class:"submit" %>
  </div>
<% end %>

app/views/yuks/_yuk.html.erb
<div id="<%= dom_id yuk %>">
</div>

app/views/yuks/edit.html.erb
<br/>
<div class="card" style="width: 80%;">
  <div class="card-header">
    <h1>Editing yuk</h1>
  </div>
  <div class="card-body">
    <%= render "form", yuk: @yuk %>
    <br>
    <div class="row">
    <%= link_to "Show this yuk", @yuk , class:"allbuttons col-6 text-center" %> 
    <%= link_to "Back to yuks", yuks_path , class:"allbuttons col-6 text-center"  %>
      </div>
  </div>
</div>

app/views/yuks/index.html.erb
<br/>
<div class="card" style="width: 80%;">
  <div class="card-header">
    <h1>Attachments</h1>
  </div>

  <div class="card-body">
    <%= render "form", yuk: @yuk %>
    <div id="yuks">
      <% @yuks.each do |yuk| %>
        <% if yuk.yuker.attached? %>
        <%= link_to yuk.yuker.filename,  rails_blob_path(yuk.yuker, disposition: "attachment") %> <br>
      <div class="row">
        <%= link_to 'Delete', [yuk.project, yuk], 'data-turbo-method': :delete,class: "btn btn-danger btn-hover button rounded-pill p-2 more-link col-2 text-center"  %>
      </div>
        <br>
        <% end %>
      <% end %>
    </div>
    <%= link_to "Back", project_path(@project) , class:"allbuttons" %>
  </div>
  <style>
  .button{
        padding-left: 20px;
        display: block;
        margin: 0 auto;
        padding: 0 20px;
        background: #ffa580;
        border: 1px solid #000;
        box-shadow: 5px 5px #95A4FF;
      }
  </style>
</div>

app/views/yuks/new.html.erb
<div class="card"style="width: 80%;">
  <div class="card-header">
  <h1>New yuk</h1>
  </div>
  <div class="card-body">
    <%= render "form", yuk: @yuk %>
  <br>
    <%= link_to "Back to yuks", yuks_path , class:"allbuttons" %>
  </div>
</div>

app/views/yuks/show.html.erb
<div class="card" style="width: 80%;">
  <div class="card-header">
    <%= render @yuk %>
  </div>

  <div class="card-body">
    <div class="row">
      <%= link_to "Edit this yuk", edit_yuk_path(@yuk) , class:"allbuttons col-6 text-center" %>
      <%= link_to "Back to yuks", yuks_path , class:"allbuttons col-6 text-center"%>
    </div>
    <%= button_to "Destroy this yuk", @yuk, method: :delete , class:"btn btn-danger btn-hover button rounded-pill p-2 more-link col-2 text-center" %>
  </div>
  <style>
  .button{
        padding-left: 20px;
        display: block;
        margin: 0 auto;
        padding: 0 20px;
        background: #ffa580;
        border: 1px solid #000;
        box-shadow: 5px 5px #95A4FF;
      }
  </style>
</div>