config/routes.rb
Rails.application.routes.draw do
  resources :ishbers
  root "projects#index"
  resources :tgers
  
  resources :tgs do
    resources :tgers
  end
  resources :yuks
  resources :projects do
    resources :yuks
    resources :tgs
    resources :ishbers
  end
  devise_for :users

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :yuks, dependent: :destroy
  has_many :tgs, dependent: :destroy
  has_many :ishbers, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1 or /projects/1.json
  def show
    if current_user != @project.user
      redirect_to projects_path
    end
  end

  # GET /projects/new
  def new
    @project = current_user.projects.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="all">
  <br/>
    <%= form_with(model: project) do |form| %>
    <% if project.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
          <% project.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3 row">
      <%= form.label :theme, class: "col-sm-2 col-form-label", style: "display: block" %>
      <div class="col-sm-10">
      <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="mb-3 row">
      <%= form.label :description, class: "col-sm-2 col-form-label", style: "display: block" %>
      <div class="col-sm-10">
      <%= form.text_area :description, class: "form-control" %>
      </div>
    </div>

    <%= form.number_field :user_id, id: :project_user_id, value: current_user.id, type: :hidden %>

    <div >
      <%= form.submit class:"btn btn-danger me-md-2 btn-hover button col-3 p-2 rounded-pill" %>
    </div>
    <style>
    .createbutton{
      color: red;
    }
    .button{
    background: #ffa580;
    border: 1px solid #000;
    box-shadow: 5px 5px #95A4FF;
    color: #000;
  }
    </style>
  <% end %>
</div>

app/views/projects/_project.html.erb
<br/>
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<br/>
<div class="card" style="width: 80%;">
  <div class="card-header">
    <h1>Editing project</h1>
  </div>

  <div class="card-body">
    <%= render "form", project: @project %>
    <br>
    <div class="row">
      <%= link_to "Show this project", @project , class:"allbuttons col-5 rounded-pill"%>
      <%= link_to "Back to projects", projects_path , class:"allbuttons col-5 rounded-pill"%>
    </div>
    <style>
    .card{
    background: #F8F4E5;
    border: 1px solid #000;
    box-shadow: 15px 15px #ffa580;
  }
  .allbuttons{
    text-align: center;
    padding-left: 20px;
    display: block;
    margin: 0 auto;
    padding: 0 20px;
    background: #ffa580;
    border: 1px solid #000;
    box-shadow: 5px 5px #95A4FF;
    color: #000;
  }
    </style>
  </div>
</div>

app/views/projects/index.html.erb
<br/>
<div class="card" style="width: 80%;">
  <div class="card-header">
    <h1>Projects</h1>
  </div>

  <div class="card-body">
    <div id="projects" >
      <div class="texts">
        <% @projects.each do |project| %>
        <%= render project %>
      </div>
      <div class="row p-2">
        <p>
          <%= link_to "Show this project", project , class:"btn btn-danger me-md-2 btn-hover  buttons col-4 p-1" %>
        </p>
      </div>
      <% end %>
    </div>

     <br/>
     <%= link_to "New project", new_project_path , class:"btn btn-danger me-md-2 btn-hover  buttons col-4 p-1"%>
    <%= button_to "Log Out", destroy_user_session_path, class:"btn btn-danger me-md-2 btn-hover button", method: :delete %>
  </div>
</div>
<style>
.card-body{
  background: #f8f4e5;
}
.texts{
  border-bottom: 1px solid black;
}
.button{
    padding-left: 20px;
    display: block;
    margin: 0 auto;
    padding: 0 20px;
    background: #ffa580;
    border: 1px solid #000;
    box-shadow: 5px 5px #95A4FF;
    color: #000;
  }
  .buttons{
    # padding-left: 20px;
    # display: grid;
    text-align: center;
    color: #000;
    margin: 0 auto;
    padding: 0 20px;
    background: #ffa580;
    border: 1px solid #000;
    box-shadow: 5px 5px #95A4FF;
  }
.card{
    font-size: 16pt;
    font-family: "Fjalla One";
    border: 1px solid #000;
    box-shadow: 15px 15px #ffa580;
    
  }
</style>

app/views/projects/new.html.erb
<br/>
<div class="card" style="width: 80%;">
  <div class="card-header">
    <h1>New project</h1>
  </div>

  <div class="card-body">
    <%= render "form", project: @project %>
    <br>
    <div>
      <%= link_to "Back to projects", projects_path , class:"allbuttons col-3 btn btn-danger me-md-2 btn-hover p-1 rounded-pill"%>
    </div>
    <style>
    .card{
      background: #F8F4E5;
      border: 1px solid #000;
      box-shadow: 15px 15px #ffa580;
    }
    .allbuttons{
    padding-left: 20px;
    display: block;
    margin: 0 auto;
    padding: 0 20px;
    background: #ffa580;
    border: 1px solid #000;
    box-shadow: 5px 5px #95A4FF;
    color: #000;
  }
    </style>
  </div>
</div>

app/views/projects/show.html.erb
<br/>
<div class="card" style="width: 80%;">
  <div class="card-header">
    <%= render @project %>
  </div>

  <div class="card-body">
    <div class="row">
      <%= link_to "Edit this project", edit_project_path(@project) , class:"allbuttons col-6" %>
      <%= link_to "Back to projects", projects_path , class:"allbuttons col-6" %> 
    </div>
    <div class="">
    <%= button_to "Delete this project", @project, method: :delete , class:"btn btn-danger btn-hover button rounded-pill p-2 col-3"%>
    </div>
    <div class="row">
      <%= link_to "Messages", project_tgs_path(@project) , class:"allbuttons col-4"%>  
      <%= link_to "Attachments", project_yuks_path(@project) , class:"allbuttons col-4"%>
      <%= link_to  "To-Dos", project_ishbers_path(@project) , class:"allbuttons col-4"%>
      </div>
  </div>
  <style>
  .button{
    padding-left: 20px;
    display: block;
    margin: 0 auto;
    padding: 0 20px;
    background: #ffa580;
    border: 1px solid #000;
    box-shadow: 5px 5px #95A4FF;
  }
  .card{
    background: #F8F4E5;
    border: 1px solid #000;
    box-shadow: 15px 15px #ffa580;
  }
  .allbuttons{
    padding: 20px;
    text-align: center;
  }
  </style>
</div>