config/routes.rb
Rails.application.routes.draw do
  resources :ishbers
  root "projects#index"
  resources :tgers
  
  resources :tgs do
    resources :tgers
  end
  resources :yuks
  resources :projects do
    resources :yuks
    resources :tgs
    resources :ishbers
  end
  devise_for :users

end

app/models/tg.rb
class Tg < ApplicationRecord
  belongs_to :project
  has_many :tgers, dependent: :destroy
  
end

app/controllers/tgs_controller.rb
class TgsController < ApplicationController
  before_action :set_tg, only: %i[ show edit update destroy ]
  before_action :set_project, only: %i[index new ]
  # GET /tgs or /tgs.json
  def index
    @tgs = @project.tgs
    @tgs.each do |tg|
      if tg.project.user != current_user
        redirect_to root_path
      end
    end
  end

  # GET /tgs/1 or /tgs/1.json
  def show
    @tger = @tg.tgers.new
    @tgers = @tg.tgers
  end

  # GET /tgs/new
  def new
    @tg = @project.tgs.new
  end

  # GET /tgs/1/edit
  def edit
  end

  # POST /tgs or /tgs.json
  def create
    @tg = Tg.new(tg_params)

    respond_to do |format|
      if @tg.save
        @tgp = @tg.project_id
        format.html { redirect_to project_tgs_path(@tgp), notice: "Tg was successfully created." }
        format.json { render :show, status: :created, location: @tg }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tgs/1 or /tgs/1.json
  def update
    respond_to do |format|
      if @tg.update(tg_params)
        format.html { redirect_to tg_url(@tg), notice: "Tg was successfully updated." }
        format.json { render :show, status: :ok, location: @tg }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tgs/1 or /tgs/1.json
  def destroy
    @tg.destroy

    respond_to do |format|
      format.html { redirect_to project_tgs_path(@tg.project_id), notice: "Tg was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tg
      @tg = Tg.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Only allow a list of trusted parameters through.
    def tg_params
      params.require(:tg).permit(:name, :description, :project_id)
    end
end

app/helpers/tgs_helper.rb
module TgsHelper
end

app/views/tgs/_form.html.erb
<%= form_with(model: tg) do |form| %>
  <% if tg.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tg.errors.count, "error") %> prohibited this tg from being saved:</h2>

      <ul>
        <% tg.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 row">
    <%= form.label :name,  class: "col-sm-2 col-form-label", style: "display: block" %>
    <div class="col-sm-10">
    <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= form.label :description,  class: "col-sm-2 col-form-label", style: "display: block" %>
    <div class="col-sm-10">
    <%= form.text_area :description , class: "form-control"%>
    </div>
  </div>

  <div class="mb-3 row">
    <%= form.text_field :project_id, type: :hidden %>
  </div>

  <div>
    <%= form.submit class:"submit" %>
  </div>
 
<% end %>

app/views/tgs/_tg.html.erb
<div id="<%= dom_id tg %>">
  <p>
    <strong>Name:</strong>
    <%= tg.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= tg.description %>
  </p>

</div>

app/views/tgs/edit.html.erb
<div class="card" style="width: 80%;">
  <div class="card-header">
    <h1>Editing Messages</h1>
  </div>

  <%= render "form", tg: @tg %>
  <br>

  <div class="card-body row">
    <%= link_to "Show this tg", @tg , class:"allbuttons col-6 text-center" %> 
    <%= link_to "Back", tg_path(@tg) , class:"allbuttons col-6 text-center" %>
  </div>
</div>

app/views/tgs/index.html.erb
<br/>
<div class="card" style="width: 80%;">
  <div class="card-header">
    <h1>Messenge</h1>
  </div>

  <div class="card-body">
    <div id="tgs">
      <% @tgs.each do |tg| %>
        <%= render tg %>
        <p class="row">
          <%= link_to "Show this tg", tg , class:"allbuttons col-12 text-center"%>
        </p>
      <% end %>
    </div>
    <div class="row link">
      <%= link_to "New tg", new_project_tg_path(@project), class:"allbuttons col-6" %> <br>
      <%= link_to "Back", project_path(@project) , class:"allbuttons col-6"%>
    </div>
    <style>
      .link{
        text-align: center;
      }
      .card{
        background: #F8F4E5;
        border: 1px solid #000;
        box-shadow: 15px 15px #ffa580;
      }
    </style>
  </div>
</div>

app/views/tgs/new.html.erb
<br/>
<div class="card" style="width: 80%;">
  <div class="card-header">
    <h1>New Messenge</h1>
  </div>
  <div class="card-body">
    <%= render "form", tg: @tg %>
    <br>
    <%= link_to "Back to tgs", project_tgs_path(@project) , class:"allbuttons"%>
  </div>
  <style>
  .card{
    background: #F8F4E5;
    border: 1px solid #000;
    box-shadow: 15px 15px #ffa580;
  }
  
  </style>
</div>

app/views/tgs/show.html.erb
<br/>
<div class="card p-3" style="width: 80%;">
  <%= render @tg %>

  <div class="card-body">
  <div class="row">
    <%= link_to "Edit this tg", edit_tg_path(@tg), class:"allbuttons col-6 text-center" %>
    <%= link_to "Back to tgs", project_tgs_path(@tg.project), class:"allbuttons col-6 text-center" %>
  </div>
    <%= button_to "Destroy this tg", @tg, method: :delete , class:"btn btn-danger me-md-2 btn-hover  buttons p-2" %>
  <div class="row p-3">
    <%= render "tgers/form", tger: @tger , class:"allbuttons" %>
  </div>
    <br />
    <% @tgers.each do |tger| %>
      <p><%= tger.title %></p>
      <% if tger.title %>
      <%= button_to "Delete this tg", tger, method: :delete, class:"btn btn-danger me-md-2 btn-hover buttons" %>
      <% end %>
    <% end %>
  </div>
  <style>
      .buttons{
        text-align: center;
        color: #000;
        margin: 0 auto;
        padding: 0 20px;
        background: #ffa580;
        border: 1px solid #000;
        box-shadow: 5px 5px #95A4FF;
      }
  </style>
</div>